/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinksSof implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long linkId;
    private Long countOfAnswers;
    private Long countOfComments;

    public LinksSof() {
    }

    public LinksSof(LinksSof value) {
        this.id = value.id;
        this.linkId = value.linkId;
        this.countOfAnswers = value.countOfAnswers;
        this.countOfComments = value.countOfComments;
    }

    @ConstructorProperties({"id", "linkId", "countOfAnswers", "countOfComments"})
    public LinksSof(
        @NotNull Long id,
        @NotNull Long linkId,
        @NotNull Long countOfAnswers,
        @NotNull Long countOfComments
    ) {
        this.id = id;
        this.linkId = linkId;
        this.countOfAnswers = countOfAnswers;
        this.countOfComments = countOfComments;
    }

    /**
     * Getter for <code>LINKS_SOF.ID</code>.
     */
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINKS_SOF.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINKS_SOF.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINKS_SOF.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINKS_SOF.COUNT_OF_ANSWERS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountOfAnswers() {
        return this.countOfAnswers;
    }

    /**
     * Setter for <code>LINKS_SOF.COUNT_OF_ANSWERS</code>.
     */
    public void setCountOfAnswers(@NotNull Long countOfAnswers) {
        this.countOfAnswers = countOfAnswers;
    }

    /**
     * Getter for <code>LINKS_SOF.COUNT_OF_COMMENTS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountOfComments() {
        return this.countOfComments;
    }

    /**
     * Setter for <code>LINKS_SOF.COUNT_OF_COMMENTS</code>.
     */
    public void setCountOfComments(@NotNull Long countOfComments) {
        this.countOfComments = countOfComments;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LinksSof other = (LinksSof) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.countOfAnswers == null) {
            if (other.countOfAnswers != null) {
                return false;
            }
        } else if (!this.countOfAnswers.equals(other.countOfAnswers)) {
            return false;
        }
        if (this.countOfComments == null) {
            if (other.countOfComments != null) {
                return false;
            }
        } else if (!this.countOfComments.equals(other.countOfComments)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.countOfAnswers == null) ? 0 : this.countOfAnswers.hashCode());
        result = prime * result + ((this.countOfComments == null) ? 0 : this.countOfComments.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinksSof (");

        sb.append(id);
        sb.append(", ").append(linkId);
        sb.append(", ").append(countOfAnswers);
        sb.append(", ").append(countOfComments);

        sb.append(")");
        return sb.toString();
    }
}
