/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinksSof implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long linkId;
    private Long countofanswers;
    private Long countofcomments;

    public LinksSof() {
    }

    public LinksSof(LinksSof value) {
        this.id = value.id;
        this.linkId = value.linkId;
        this.countofanswers = value.countofanswers;
        this.countofcomments = value.countofcomments;
    }

    @ConstructorProperties({"id", "linkId", "countofanswers", "countofcomments"})
    public LinksSof(
        @NotNull Long id,
        @NotNull Long linkId,
        @NotNull Long countofanswers,
        @NotNull Long countofcomments
    ) {
        this.id = id;
        this.linkId = linkId;
        this.countofanswers = countofanswers;
        this.countofcomments = countofcomments;
    }

    /**
     * Getter for <code>LINKS_SOF.ID</code>.
     */
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINKS_SOF.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINKS_SOF.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINKS_SOF.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINKS_SOF.COUNTOFANSWERS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountofanswers() {
        return this.countofanswers;
    }

    /**
     * Setter for <code>LINKS_SOF.COUNTOFANSWERS</code>.
     */
    public void setCountofanswers(@NotNull Long countofanswers) {
        this.countofanswers = countofanswers;
    }

    /**
     * Getter for <code>LINKS_SOF.COUNTOFCOMMENTS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountofcomments() {
        return this.countofcomments;
    }

    /**
     * Setter for <code>LINKS_SOF.COUNTOFCOMMENTS</code>.
     */
    public void setCountofcomments(@NotNull Long countofcomments) {
        this.countofcomments = countofcomments;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LinksSof other = (LinksSof) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.countofanswers == null) {
            if (other.countofanswers != null) {
                return false;
            }
        } else if (!this.countofanswers.equals(other.countofanswers)) {
            return false;
        }
        if (this.countofcomments == null) {
            if (other.countofcomments != null) {
                return false;
            }
        } else if (!this.countofcomments.equals(other.countofcomments)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.countofanswers == null) ? 0 : this.countofanswers.hashCode());
        result = prime * result + ((this.countofcomments == null) ? 0 : this.countofcomments.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinksSof (");

        sb.append(id);
        sb.append(", ").append(linkId);
        sb.append(", ").append(countofanswers);
        sb.append(", ").append(countofcomments);

        sb.append(")");
        return sb.toString();
    }
}
