/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables;

import edu.java.jooq.DefaultSchema;
import edu.java.jooq.Keys;
import edu.java.jooq.tables.records.LinksSofRecord;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinksSof extends TableImpl<LinksSofRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKS_SOF</code>
     */
    public static final LinksSof LINKS_SOF = new LinksSof();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinksSofRecord> getRecordType() {
        return LinksSofRecord.class;
    }

    /**
     * The column <code>LINKS_SOF.ID</code>.
     */
    public final TableField<LinksSofRecord, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>LINKS_SOF.LINK_ID</code>.
     */
    public final TableField<LinksSofRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKS_SOF.COUNT_OF_ANSWERS</code>.
     */
    public final TableField<LinksSofRecord, Long> COUNT_OF_ANSWERS =
        createField(DSL.name("COUNT_OF_ANSWERS"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKS_SOF.COUNT_OF_COMMENTS</code>.
     */
    public final TableField<LinksSofRecord, Long> COUNT_OF_COMMENTS =
        createField(DSL.name("COUNT_OF_COMMENTS"), SQLDataType.BIGINT.nullable(false), this, "");

    private LinksSof(Name alias, Table<LinksSofRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinksSof(Name alias, Table<LinksSofRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKS_SOF</code> table reference
     */
    public LinksSof(String alias) {
        this(DSL.name(alias), LINKS_SOF);
    }

    /**
     * Create an aliased <code>LINKS_SOF</code> table reference
     */
    public LinksSof(Name alias) {
        this(alias, LINKS_SOF);
    }

    /**
     * Create a <code>LINKS_SOF</code> table reference
     */
    public LinksSof() {
        this(DSL.name("LINKS_SOF"), null);
    }

    public <O extends Record> LinksSof(Table<O> child, ForeignKey<O, LinksSofRecord> key) {
        super(child, key, LINKS_SOF);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<LinksSofRecord, Long> getIdentity() {
        return (Identity<LinksSofRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<LinksSofRecord> getPrimaryKey() {
        return Keys.PK_LINKS_SOF;
    }

    @Override
    @NotNull
    public LinksSof as(String alias) {
        return new LinksSof(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinksSof as(Name alias) {
        return new LinksSof(alias, this);
    }

    @Override
    @NotNull
    public LinksSof as(Table<?> alias) {
        return new LinksSof(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksSof rename(String name) {
        return new LinksSof(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksSof rename(Name name) {
        return new LinksSof(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksSof rename(Table<?> name) {
        return new LinksSof(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function4<? super Long, ? super Long, ? super Long, ? super Long, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
