app:
  use-queue : true
  linkDelay: 30
  gitUrl: "https://api.github.com"
  stackUrl: "https://api.stackexchange.com/2.3"
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 5s
  database-access-type: jpa
  retry:
    trigger: server-client
    strategy: const
    max-attempts: 3
    delay: 5
  bucket:
    refill: 5
    capacity: 10
    timeout: 1
  kafka:
    partitions-num: 10
    replicas-num: 1
    topics: topic1

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    consumer:
      auto-offset-reset: earliest
    bootstrapServers: localhost:29092

server:
  port: 1020

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
