app:
  git-hub-base-url: "https://api.github.com"
  stack-overflow-base-url: "https://api.stackexchange.com/2.3"
  scheduler:
    enable: true
    interval: 1000
    force-check-delay: 1000

spring:
  application:
    name: scrapper

server:
  port: 1010

logging:
  config: classpath:log4j2-plain.xml
