app:
  telegram-token: 6813754853:AAFwcgsB1_mYknKwVDcSip8eI3wsEKyzUzc

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
