app:
  telegram-token: ${TELEGRAM_API_KEY}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8070

springdoc:
  swagger-ui:
    path: swagger-ui

logging:
  config: classpath:log4j2-plain.xml
