/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq;

import edu.java.jooq.tables.Chat;
import edu.java.jooq.tables.Link;
import edu.java.jooq.tables.LinksSof;
import edu.java.jooq.tables.records.ChatRecord;
import edu.java.jooq.tables.records.LinkRecord;
import edu.java.jooq.tables.records.LinksSofRecord;
import javax.annotation.processing.Generated;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> PK_CHAT =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("PK_CHAT"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<LinkRecord> PK_LINK =
        Internal.createUniqueKey(Link.LINK, DSL.name("PK_LINK"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinksSofRecord> PK_LINKS_SOF = Internal.createUniqueKey(LinksSof.LINKS_SOF,
        DSL.name("PK_LINKS_SOF"),
        new TableField[] {LinksSof.LINKS_SOF.ID},
        true
    );
}
