/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq;

import edu.java.jooq.tables.Chat;
import edu.java.jooq.tables.Link;
import edu.java.jooq.tables.LinksSof;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>LINKS_SOF</code>.
     */
    public static final LinksSof LINKS_SOF = LinksSof.LINKS_SOF;
}
