/*
 * This file is generated by jOOQ.
 */

package edu.java.jooq.tables.records;

import edu.java.jooq.tables.LinksSof;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinksSofRecord extends UpdatableRecordImpl<LinksSofRecord> implements Record4<Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS_SOF.ID</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS_SOF.ID</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS_SOF.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS_SOF.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>LINKS_SOF.COUNT_OF_ANSWERS</code>.
     */
    public void setCountOfAnswers(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS_SOF.COUNT_OF_ANSWERS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountOfAnswers() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>LINKS_SOF.COUNT_OF_COMMENTS</code>.
     */
    public void setCountOfComments(@NotNull Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINKS_SOF.COUNT_OF_COMMENTS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getCountOfComments() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Long, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return LinksSof.LINKS_SOF.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return LinksSof.LINKS_SOF.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return LinksSof.LINKS_SOF.COUNT_OF_ANSWERS;
    }

    @Override
    @NotNull
    public Field<Long> field4() {
        return LinksSof.LINKS_SOF.COUNT_OF_COMMENTS;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getCountOfAnswers();
    }

    @Override
    @NotNull
    public Long component4() {
        return getCountOfComments();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getCountOfAnswers();
    }

    @Override
    @NotNull
    public Long value4() {
        return getCountOfComments();
    }

    @Override
    @NotNull
    public LinksSofRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSofRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSofRecord value3(@NotNull Long value) {
        setCountOfAnswers(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSofRecord value4(@NotNull Long value) {
        setCountOfComments(value);
        return this;
    }

    @Override
    @NotNull
    public LinksSofRecord values(
        @NotNull Long value1,
        @NotNull Long value2,
        @NotNull Long value3,
        @NotNull Long value4
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksSofRecord
     */
    public LinksSofRecord() {
        super(LinksSof.LINKS_SOF);
    }

    /**
     * Create a detached, initialised LinksSofRecord
     */
    @ConstructorProperties({"id", "linkId", "countOfAnswers", "countOfComments"})
    public LinksSofRecord(
        @NotNull Long id,
        @NotNull Long linkId,
        @NotNull Long countOfAnswers,
        @NotNull Long countOfComments
    ) {
        super(LinksSof.LINKS_SOF);

        setId(id);
        setLinkId(linkId);
        setCountOfAnswers(countOfAnswers);
        setCountOfComments(countOfComments);
    }

    /**
     * Create a detached, initialised LinksSofRecord
     */
    public LinksSofRecord(edu.java.jooq.tables.pojos.LinksSof value) {
        super(LinksSof.LINKS_SOF);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setCountOfAnswers(value.getCountOfAnswers());
            setCountOfComments(value.getCountOfComments());
        }
    }
}
